name: dw_image_picker_platform_interface
description: A common platform interface for the dw_image_picker plugin.
repository: https://github.com/DeveloperWaybee/dw_image_picker/tree/main/dw_image_picker_platform_interface
issue_tracker: https://github.com/DeveloperWaybee/dw_image_picker/issues

version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0