name: dw_image_picker_ios
description: iOS implementation of the dw_image_picker plugin.
repository: https://github.com/DeveloperWaybee/dw_image_picker/tree/main/dw_image_picker_ios
issue_tracker: https://github.com/DeveloperWaybee/dw_image_picker/issues

version: 1.0.5

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dw_image_picker_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      ios:
        dartPluginClass: DWImagePickerIOS
        pluginClass: DWImagePickerPlugin
