name: dw_image_picker
description: Choose images/videos from the library, crop images, and capture new photos/videos with ease.
repository: https://github.com/DeveloperWaybee/dw_image_picker/tree/main/dw_image_picker
issue_tracker: https://github.com/DeveloperWaybee/dw_image_picker/issues

version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dw_image_picker_platform_interface: ^1.0.0
  dw_image_picker_ios: ^1.0.5
  dw_image_picker_android: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: dw_image_picker_android
      ios:
        default_package: dw_image_picker_ios
